version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    command: start-dev
    environment:
      - KC_DB=dev-mem
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:Z  # for realm import (optional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      retries: 12

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    depends_on:
      - keycloak
    environment:
      # generate SECRETs before run and paste them here or use envsubst
      - OAUTH2_PROXY_COOKIE_SECRET=__GENERATE_COOKIE_SECRET__
      - OAUTH2_PROXY_CLIENT_ID=blog-client
      - OAUTH2_PROXY_CLIENT_SECRET=__KEYCLOAK_CLIENT_SECRET__
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/blog-realm
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://httpbin:80
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    ports:
      - "4180:4180"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - oauth2-proxy
      - httpbin
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

