services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_PORT=8080
      - KC_DB=dev-mem
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

    ports:
      - "8080:8080"
    networks:
      - keycloak_net
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=4UXctMb6SOnuHCo6MeVDVxI8TWPRfrLguO6SmDDqCBE=
      - OAUTH2_PROXY_CLIENT_ID=blog-client
      - OAUTH2_PROXY_CLIENT_SECRET=4UXctMb6SOnuHCo6MeVDVxI8TWPRfrLguO6SmDDqCBE=
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/blog-realm
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8081/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true  # Enables user headers like X-Auth-Request-Email
    restart: on-failure:5
    networks:
      - keycloak_net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4180/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "4180:4180"

  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
    networks:
      - keycloak_net

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    depends_on:
      oauth2-proxy:
        condition: service_healthy
      httpbin:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    networks:
      - keycloak_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  keycloak_net:
    driver: bridge
