version: "3.8"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_DB=dev-mem
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

    ports:
      - "8080:8080"
    networks:
      - keycloak_net
    volumes:
      - ./keycloak:/opt/keycloak/data/import:Z
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=0123456789abcdef0123456789abcdef
      - OAUTH2_PROXY_CLIENT_ID=blog-client
      - OAUTH2_PROXY_CLIENT_SECRET=Ck43bm93ifpp9hYbK4c2beGisq8BhYV94POP29S4KKw=
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/blog-realm
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAMS=http://httpbin:80
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    ports:
      - "4180:4180"
    restart: unless-stopped
    networks:
      - keycloak_net

  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
    networks:
      - keycloak_net

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    depends_on:
      oauth2-proxy:
        condition: service_healthy
      httpbin:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    networks:
      - keycloak_net

networks:
  keycloak_net:
    driver: bridge
